### PR TITLE
Update sparse_weights.py

### LINKED ISSUE #55: test_sparse_weights_1d and test_sparse_weights_2d tests not passing
Hi,

I installed the nupic.torch framework using _python setup.py develop_ as in the readme file. However, when I reach the test phase, all tests are successfully completed except test_sparse_weights_1d and test_sparse_weights_2d. I'm working on windows 10 with python 3.7.6 and pytorch 1.3. 

The error Traceback is as follows:

ERROR: test_sparse_weights_1d (tests.sparse_weights_test.TestSparseWeights)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\lenovo\documents\github\nupic.torch\tests\sparse_weights_test.py", line 36, in test_sparse_weights_1d
    sparse = SparseWeights(linear, percent_on)
  File "C:\Users\Lenovo\Documents\GitHub\nupic.torch\nupic\torch\modules\sparse_weights.py", line 120, in __init__
    super(SparseWeights, self).__init__(module, weight_sparsity)
  File "C:\Users\Lenovo\Documents\GitHub\nupic.torch\nupic\torch\modules\sparse_weights.py", line 78, in __init__
    self.rezero_weights()
  File "C:\Users\Lenovo\Documents\GitHub\nupic.torch\nupic\torch\modules\sparse_weights.py", line 143, in rezero_weights
    self.module.weight.data[zero_idx] = 0.0
IndexError: tensors used as indices must be long, byte or bool tensors

======================================================================
ERROR: test_sparse_weights_2d (tests.sparse_weights_test.TestSparseWeights)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\lenovo\documents\github\nupic.torch\tests\sparse_weights_test.py", line 53, in test_sparse_weights_2d
    sparse = SparseWeights2d(cnn, percent_on)
  File "C:\Users\Lenovo\Documents\GitHub\nupic.torch\nupic\torch\modules\sparse_weights.py", line 159, in __init__
    super(SparseWeights2d, self).__init__(module, weight_sparsity)
  File "C:\Users\Lenovo\Documents\GitHub\nupic.torch\nupic\torch\modules\sparse_weights.py", line 78, in __init__
    self.rezero_weights()
  File "C:\Users\Lenovo\Documents\GitHub\nupic.torch\nupic\torch\modules\sparse_weights.py", line 187, in rezero_weights
    self.module.weight.data.view(self.module.out_channels, -1)[zero_idx] = 0.0
IndexError: tensors used as indices must be long, byte or bool tensors

----------------------------------------------------------------------
Ran 21 tests in 0.109s

FAILED (errors=2)
Test failed: <unittest.runner.TextTestResult run=21 errors=2 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=21 errors=2 failures=0>

### PR DESCRIPTION
**Pull request by ayaz-amin**
Fixes #55

Fixed this index error:
```
IndexError: tensors used as indices must be long, byte or bool tensors
```

### CODE REVIEW

**Comment by rhyolight** [comment]
Thank you for your contribution, @ayaz-amin. Please sign our [contributor license agreement](https://numenta.org/licenses/contrib/) and we will review your PR.

**Comment by ayaz-amin** [comment]
All done!

**Comment by rhyolight** [comment]
The only reservation I have about this PR is that we don't have a Windows build in our Circle CI config. So it's not really being tested at all. We have tested that nothing broke in the current build at least 👍 . 

@ayaz-amin Are you interested in updating [`.circleci/config.yml`](https://github.com/ayaz-amin/nupic.torch/blob/master/.circleci/config.yml) so that we have a Windows build? There are instructions [here](https://circleci.com/docs/2.0/hello-world-windows/).

**Comment by ayaz-amin** [comment]
I will try, although I may not be able to do it (I have zero experience using continuous integration).

**Comment by ayaz-amin** [comment]
Turns out it wasn't so hard! :)

**Comment by rhyolight** [comment]
Great! Except it is not running! 😜 

```
# WARNING: It looks like your config might use features only available in 2.1 config
# Your config version: 2
# Possible 2.1 features found:
#   Found 'orbs' key at top level
```

Try updating the version to `2.1` please?

**Comment by rhyolight** [comment]
Hmm, might not be as simple as you thought? 2.1 brings some new features that seem to have broken something. This looks helpful: https://discuss.circleci.com/t/circleci-2-1-config-overview/26057?gclid=EAIaIQobChMI_uDQjtCa5wIV5B6tBh1LzgrzEAAYASAAEgKEXvD_BwE

**Comment by ayaz-amin** [comment]
Ah, now it makes sense!

**Comment by mvacaporale** [comment]
> Fixes #55
> 
> Fixed this index error:
> 
> ```
> IndexError: tensors used as indices must be long, byte or bool tensors
> ```

Thanks for your help on this issue. Here's something to consider:
The tensors should have been long because we're converting a `np.array` of datatype `np.long` via `torch.from_numpy` (see lines 139 and 183 in `sparse_weights.py`)
I’m curious why the conversion would yield a tensor that’s not a `torch.LongTensor`.

Regardless, it doesn’t hurt to add the type conversion to `rezero_weights` as done in your PR.
However, I think the fix should also be made at the source when the zero weights are first saved. That is, lines 139 and 183 should read:
`return torch.from_numpy(zero_indices.transpose()).long()`

**Comment by rhyolight** [comment]
@ayaz-amin If you don't want to worry about the Windows build, you can just focus on the original issue and maybe we can work together to get a windows build working in another PR? I will approve this change without a Windows build, but I certainly would love to have one.

**Comment by ayaz-amin** [comment]
I think its best to leave that to another PR. I am still trying to get the basic ideas of setting up a CI.

**Comment by ayaz-amin** [comment]
I opened a new PR for a Windows build.

**Comment by rhyolight** [comment]
@ayaz-amin What do you think about the feedback from @mvacaporale above?

**Comment by ayaz-amin** [comment]
I think its good. It could just be a bug in the numpy build, as @mvacaporale mentioned.

**Comment by rhyolight** [comment]
@ayaz-amin thanks for your contribution. I look forward to working with you on #57.

**Pull request merged**
